let hotelRooms = [
{
  "roomNumber": "Room 1",
  "roomType": "Budget",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 2",
  "roomType": "Budget",
  "numberOfPeople": "3",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 3",
  "roomType": "Budget",
  "numberOfPeople": "2",
  "status": "Occupied",
  "checkInDate": "2018-10-08",
  "checkOutDate": "2019-01-27",
  "guest": "Adje van Bavel",
  "email": "adje.van.bavel@hotmail.com",
  "telephone": "",
  "country": "The Netherlands",
  "checkedIn": true,
  "hasPaid": false,
  "accessories": ["Crib", "Big Screen TV"]
},
{
  "roomNumber": "Room 4",
  "roomType": "Budget",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 5",
  "roomType": "Budget",
  "numberOfPeople": "4",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 6",
  "roomType": "Budget",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 7",
  "roomType": "Budget",
  "numberOfPeople": "3",
  "status": "Occupied",
  "checkInDate": "2018-12-12",
  "checkOutDate": "2018-12-30",
  "guest": "Bill Gates",
  "email": "thebillionaire@windhoos.com",
  "telephone": "0015554895",
  "country": "United States",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 8",
  "roomType": "Budget",
  "numberOfPeople": "4",
  "status": "Occupied",
  "checkInDate": "2019-02-02",
  "checkOutDate": "2019-02-03",
  "guest": "Bas van Toor",
  "email": "",
  "telephone": "0031102484000",
  "country": "The Netherlands",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 9",
  "roomType": "Budget",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 10",
  "roomType": "Budget",
  "numberOfPeople": "3",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 11",
  "roomType": "Standard",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 12",
  "roomType": "Standard",
  "numberOfPeople": "4",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 13",
  "roomType": "Standard",
  "numberOfPeople": "3",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 14",
  "roomType": "Standard",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 15",
  "roomType": "Standard",
  "numberOfPeople": "2",
  "status": "Occupied",
  "checkInDate": "2019-11-06",
  "checkOutDate": "2019-11-10",
  "guest": "Mahmoud Ahmadinejad",
  "email": "",
  "telephone": "009199323211",
  "country": "Iran",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 16",
  "roomType": "Luxurious",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 17",
  "roomType": "Luxurious",
  "numberOfPeople": "2",
  "status": "Occupied",
  "checkInDate": "2018-12-31",
  "checkOutDate": "2019-01-04",
  "guest": "Donald J. Trump",
  "email": "therealdonaldtrump@whitehouse.gov",
  "telephone": "",
  "country": "United States",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 18",
  "roomType": "Luxurious",
  "numberOfPeople": "2",
  "status": "Occupied",
  "checkInDate": "2018-11-11",
  "checkOutDate": "2018-11-25",
  "guest": "Pietje Puk",
  "email": "pietjepuk@somedomain.com",
  "telephone": "325783826994",
  "country": "Belgium",
  "checkedIn": true,
  "hasPaid": false,
  "accessories": ["Crib", "Big Screen TV", "Espresso Machine"]
},
{
  "roomNumber": "Room 19",
  "roomType": "Luxurious",
  "numberOfPeople": "3",
  "status": "Occupied",
  "checkInDate": "2018-10-06",
  "checkOutDate": "2019-01-01",
  "guest": "Jan Modaal",
  "email": "",
  "telephone": "00312937509",
  "country": "The Netherlands",
  "checkedIn": true,
  "hasPaid": false,
  "accessories": ""
},
{
  "roomNumber": "Room 20",
  "roomType": "Luxurious",
  "numberOfPeople": "2",
  "status": "Vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": "",
  "checkedIn": false,
  "hasPaid": false,
  "accessories": ""
}];
