let hotelKamers = [
  {"kamerNummer": "kamer 1",
   "kamerType": "economy class",
   "aantalPersonen": "2",
   "status": "vrij",
   "checkInDate": "",
   "checkOutDate": "",
   "guest": "",
   "email": "",
   "telephone": ""
 },
 {"kamerNummer": "kamer 2",
  "kamerType": "economy class",
  "aantalPersonen": "3",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 3",
  "kamerType": "economy class",
  "aantalPersonen": "2",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 4",
  "kamerType": "economy class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 5",
  "kamerType": "economy class",
  "aantalPersonen": "4",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 6",
  "kamerType": "economy class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 7",
  "kamerType": "economy class",
  "aantalPersonen": "3",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 8",
  "kamerType": "economy class",
  "aantalPersonen": "4",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 9",
  "kamerType": "economy class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 10",
  "kamerType": "economy class",
  "aantalPersonen": "3",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 11",
  "kamerType": "lux",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 12",
  "kamerType": "lux",
  "aantalPersonen": "4",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 13",
  "kamerType": "lux",
  "aantalPersonen": "3",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 14",
  "kamerType": "lux",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 15",
  "kamerType": "lux",
  "aantalPersonen": "2",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 16",
  "kamerType": "business class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 17",
  "kamerType": "business class",
  "aantalPersonen": "2",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 18",
  "kamerType": "business class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 19",
  "kamerType": "business class",
  "aantalPersonen": "3",
  "status": "bezet",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 },
 {"kamerNummer": "kamer 20",
  "kamerType": "business class",
  "aantalPersonen": "2",
  "status": "vrij",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": ""
 }
];
