let hotelRooms = [
  {"roomNumber": "room 1",
   "roomType": "budget",
   "numberOfPeople": "2",
   "status": "vacant",
   "checkInDate": "",
   "checkOutDate": "",
   "guest": "",
   "email": "",
   "telephone": "",
   "country": ""
 },
 {"roomNumber": "room 2",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 3",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "2019-01-31",
  "checkOutDate": "2019-12-31",
  "guest": "Adje van Bavel",
  "email": "adje.van.bavel@hotmail.com",
  "telephone": "",
  "country": "The Netherlands"
},
{
  "roomNumber": "room 4",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 5",
  "roomType": "budget",
  "numberOfPeople": "4",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 6",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 7",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "occupied",
  "checkInDate": "2018-12-12",
  "checkOutDate": "2018-12-30",
  "guest": "Bill Gates",
  "email": "thebillionaire@windhoos.com",
  "telephone": "0015554895",
  "country": "United States"
},
{
  "roomNumber": "room 8",
  "roomType": "budget",
  "numberOfPeople": "4",
  "status": "occupied",
  "checkInDate": "2019-02-02",
  "checkOutDate": "2019-02-03",
  "guest": "Bas van Toor",
  "email": "",
  "telephone": "0031102484000",
  "country": "The Netherlands"
},
{
  "roomNumber": "room 9",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 10",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 11",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 12",
  "roomType": "standard",
  "numberOfPeople": "4",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 13",
  "roomType": "standard",
  "numberOfPeople": "3",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 14",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 15",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "2019-11-06",
  "checkOutDate": "2019-11-10",
  "guest": "Mahmoud Ahmadinejad",
  "email": "",
  "telephone": "009199323211",
  "country": "Iran"
},
{
  "roomNumber": "room 16",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 17",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "2018-12-31",
  "checkOutDate": "2019-01-04",
  "guest": "Donald J. Trump",
  "email": "therealdonaldtrump@whitehouse.gov",
  "telephone": "",
  "country": "United States"
},
{
  "roomNumber": "room 18",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
},
{
  "roomNumber": "room 19",
  "roomType": "luxurious",
  "numberOfPeople": "3",
  "status": "occupied",
  "checkInDate": "2018-12-12",
  "checkOutDate": "2019-01-01",
  "guest": "Jan Modaal",
  "email": "",
  "telephone": "00312937509",
  "country": "The Netherlands"
},
{
  "roomNumber": "room 20",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "guest": "",
  "email": "",
  "telephone": "",
  "country": ""
}];
