let hotelrooms = [{
  "roomNumber": "1",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "2",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "occupied",
  "checkInDate": "02-03-2019",
  "checkOutDate": "09-03-2019",
  "firstname": "Jan",
  "surname": "Jansen",
  "email": "jan.jansen@hotmail.com",
  "telephone": "00317937409",
  "country": "The Netherlands",
  "bookingNumber": "7",
  "address": "Jansenlaan 49",
  "check": ""
},
{
  "roomNumber": "3",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "31-01-2019",
  "checkOutDate": "31-12-2019",
  "firstname": "Adje",
  "surname": "van Bavel",
  "email": "adje.van.bavel@hotmail.com",
  "telephone": "",
  "country": "The Netherlands",
  "bookingNumber": "1",
  "address": "Dommel 2",
  "check": ""
},
{
  "roomNumber": "4",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "5",
  "roomType": "budget",
  "numberOfPeople": "4",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "6",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "7",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "occupied",
  "checkInDate": "12-12-2018",
  "checkOutDate": "30-12-2018",
  "firstname": "Bill",
  "surname": "Gates",
  "email": "thebillionaire@windhoos.com",
  "telephone": "0015554895",
  "country": "United States",
  "bookingNumber": "2",
  "address": "billy lane 123",
  "check": ""
},
{
  "roomNumber": "8",
  "roomType": "budget",
  "numberOfPeople": "4",
  "status": "occupied",
  "checkInDate": "02-02-2019",
  "checkOutDate": "03-02-2019",
  "firstname": "Bas",
  "surname": "van Toor",
  "email": "",
  "telephone": "0031102484000",
  "country": "The Netherlands",
  "bookingNumber": "3",
  "address": "sesamstraat 7",
  "check": ""
},
{
  "roomNumber": "9",
  "roomType": "budget",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "10",
  "roomType": "budget",
  "numberOfPeople": "3",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "11",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "12",
  "roomType": "standard",
  "numberOfPeople": "4",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "13",
  "roomType": "standard",
  "numberOfPeople": "3",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "14",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "15",
  "roomType": "standard",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "06-11-2019",
  "checkOutDate": "10-11-2019",
  "firstname": "Mahmoud",
  "surname": "Ahmadinejad",
  "email": "",
  "telephone": "009199323211",
  "country": "Iran",
  "bookingNumber": "4",
  "address": "Pannenschuurhoven 1",
  "check": ""
},
{
  "roomNumber": "16",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "17",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "occupied",
  "checkInDate": "31-12-2018",
  "checkOutDate": "04-01-2019",
  "firstname": "Donald",
  "surname": "Trump",
  "email": "therealdonaldtrump@whitehouse.gov",
  "telephone": "",
  "country": "United States",
  "bookingNumber": "5",
  "address": "white house 1",
  "check": ""
},
{
  "roomNumber": "18",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
},
{
  "roomNumber": "19",
  "roomType": "luxurious",
  "numberOfPeople": "3",
  "status": "occupied",
  "checkInDate": "12-12-2018",
  "checkOutDate": "01-01-2019",
  "firstname": "Jan",
  "surname": "Modaal",
  "email": "",
  "telephone": "00312937509",
  "country": "The Netherlands",
  "bookingNumber": "6",
  "address": "Modaal laan 124",
  "check": ""
},
{
  "roomNumber": "20",
  "roomType": "luxurious",
  "numberOfPeople": "2",
  "status": "vacant",
  "checkInDate": "",
  "checkOutDate": "",
  "firstname": "",
  "surname": "",
  "email": "",
  "telephone": "",
  "country": "",
  "bookingNumber": "",
  "address": "",
  "check": ""
}
];
